spring.application.name=quiz-builder
server.port=9090
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/quiz-builder
spring.datasource.username=admin
spring.datasource.password=me@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernates.ddl-auto=update
# spring.jpa.properties.hibernates.dio

