spring.application.name=quiz-builder
server.port=9090
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# spring.datasource.url=jdbc:postgresql://localhost:5432/quiz-builder
  spring.datasource.url=
  spring.datasource.username=
  spring.datasource.password=
  spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernates.dio

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.document-title=Quiz Builder API
